TCPEchoServer-Thread: TCPEchoServer-Thread.c AcceptTCPConnection.c DieWithError.c CreateTCPServerSocket.c HandleTCPClient.c
	gcc -o TCPEchoServer-Thread TCPEchoServer-Thread.c AcceptTCPConnection.c DieWithError.c CreateTCPServerSocket.c HandleTCPClient.c -l pthread
