TCPEchoServer-Thread: TCPEchoServer-Thread.c AcceptTCPConnection.c ../common/DieWithError.c CreateTCPServerSocket.c HandleTCPClient.c GameRoom.c ../common/ccLemon.c Logger.c
	gcc -o TCPEchoServer-Thread TCPEchoServer-Thread.c AcceptTCPConnection.c ../common/DieWithError.c CreateTCPServerSocket.c HandleTCPClient.c GameRoom.c Logger.c ../common/ccLemon.c -I../common -lpthread
